name: sasuki
description: app for managing network systems
publish_to: "none"
version: 3.1.0+1
environment:
  sdk: ">=2.19.0 <3.0.0"

dependencies:
  analyzer: ^5.0.0
  change_app_package_name: ^1.1.0
  cupertino_icons: ^1.0.2
  dartz: ^0.10.1
  dio: ^4.0.6
  double_back_to_close_app: ^2.1.0
  encrypt: ^5.0.1
  firebase_analytics: ^10.4.2
  firebase_core: ^2.13.1
  firebase_crashlytics: ^3.3.2
  flutter:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1
  flutter_svg: ^2.0.2
  freezed: ^2.1.1
  get_it: ^7.2.0
  internet_connection_checker: ^1.0.0+1
  intl: ^0.18.0
  json_serializable: ^6.3.2
  jwt_decoder: ^2.0.1
  logger: ^1.4.0
  lottie: ^2.2.0
  material_design_icons_flutter: ^6.0.7096
  pin_code_fields: ^7.4.0
  pretty_dio_logger: ^1.1.1
  responsive_framework: ^0.2.0
  retrofit: ^3.0.1+1
  rxdart: ^0.27.5
  shared_preferences: ^2.0.15
  shimmer: ^2.0.0
  uuid: ^3.0.6

dev_dependencies:
  build_runner: ^2.2.1
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  retrofit_generator: ^4.0.3+2

flutter:
  uses-material-design: true
  assets:
    - assets/icons/drawer/
    - assets/icons/shared_icons/
    - assets/icons/specific_screen/
    - assets/images/
    - assets/json/
    - assets/error_strings.json
  fonts:
    - family: IBMPlexSans
      fonts:
        - asset: assets/font/IBMPlexSans-Regular.ttf
          weight: 400
        - asset: assets/font/IBMPlexSans-Medium.ttf
          weight: 500
        - asset: assets/font/IBMPlexSans-SemiBold.ttf
          weight: 600
        - asset: assets/font/IBMPlexSans-Bold.ttf
          weight: 700

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/sasuki_app_icon.png"
