name: sasuki
description: app for managing network systems
publish_to: "none"
version: 1.0.0+1
environment:
  sdk: ">=2.19.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  responsive_framework: ^0.2.0
  flutter_svg: ^1.1.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
flutter:
  uses-material-design: true
  assets:
    - assets/icons/drawer/
    - assets/icons/shared_icons/
    - assets/icons/specific_screen/
    - assets/images/
  fonts:
    - family: IBMPlexSans
      fonts:
        - asset: assets/font/IBMPlexSans-Regular.ttf
          weight: 400
        - asset: assets/font/IBMPlexSans-Medium.ttf
          weight: 500
        - asset: assets/font/IBMPlexSans-SemiBold.ttf
          weight: 600
        - asset: assets/font/IBMPlexSans-Bold.ttf
          weight: 700
