// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA6ym2rgxNuxeeLzlJ3R7Wz4LGLmOck8CM',
    appId: '1:130110928875:web:8a7016feae3348f2648bae',
    messagingSenderId: '130110928875',
    projectId: 'sas-radius-af46f',
    authDomain: 'sas-radius-af46f.firebaseapp.com',
    storageBucket: 'sas-radius-af46f.appspot.com',
    measurementId: 'G-FLMF61MHQ4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCVs0mnprSBkLbB1R2pQalgorTJRiHbRtU',
    appId: '1:130110928875:android:2fd2e4deb5222f2d648bae',
    messagingSenderId: '130110928875',
    projectId: 'sas-radius-af46f',
    storageBucket: 'sas-radius-af46f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyATO5McrlXgvjpZSVEepzCG-E9gXbVJ8uY',
    appId: '1:130110928875:ios:87e5a4dbf6877bcf648bae',
    messagingSenderId: '130110928875',
    projectId: 'sas-radius-af46f',
    storageBucket: 'sas-radius-af46f.appspot.com',
    iosClientId: '130110928875-bipk6tn14f6f73sqe6suik1vhdt6iosp.apps.googleusercontent.com',
    iosBundleId: 'com.snono.sasuki',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyATO5McrlXgvjpZSVEepzCG-E9gXbVJ8uY',
    appId: '1:130110928875:ios:0eebaf50ab4d5d7d648bae',
    messagingSenderId: '130110928875',
    projectId: 'sas-radius-af46f',
    storageBucket: 'sas-radius-af46f.appspot.com',
    iosClientId: '130110928875-nejl6abl8g6mr3ltgh093m4dvqer0ncm.apps.googleusercontent.com',
    iosBundleId: 'com.snono.sasuki.RunnerTests',
  );
}
